# Generated by Django 6.0.4 on 2026-04-17 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Origin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("region", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "origins",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TeaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "fermentation_level",
                    models.IntegerField(
                        choices=[
                            (0, "White Tea (0%)"),
                            (5, "Green Tea (0-5%)"),
                            (45, "Oolong Tea (15-70%)"),
                            (100, "Black Tea (100%)"),
                            (-1, "Pu'erh Tea (Post-fermented)"),
                        ],
                        help_text="Oxidation percentage",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "brewing_temp_celsius",
                    models.IntegerField(
                        help_text="Recommended brewing temperature in Celsius"
                    ),
                ),
                (
                    "brewing_time_seconds",
                    models.IntegerField(
                        help_text="Recommended brewing time in seconds"
                    ),
                ),
                ("image", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "tea categories",
                "db_table": "tea_categories",
                "ordering": ["fermentation_level"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=255)),
                (
                    "price_sgd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price in SGD (before GST)",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_inclusive",
                    models.BooleanField(
                        default=True, help_text="Whether price includes GST"
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "harvest_season",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("spring", "Spring"),
                            ("summer", "Summer"),
                            ("autumn", "Autumn"),
                            ("winter", "Winter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("harvest_year", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_grams", models.PositiveIntegerField(default=50)),
                ("is_new_arrival", models.BooleanField(default=False)),
                ("is_subscription_eligible", models.BooleanField(default=True)),
                ("image", models.URLField(blank=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="commerce.origin",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="commerce.teacategory",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-is_new_arrival", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("past_due", "Past Due"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "price_sgd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly subscription price in SGD",
                        max_digits=10,
                    ),
                ),
                ("next_billing_date", models.DateTimeField()),
                (
                    "next_curation_override",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Manual product selection for next shipment. Format: {'product_ids': [1, 2, 3]}",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, help_text="Stripe subscription ID", max_length=255
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, help_text="Stripe customer ID", max_length=255
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "Preparing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="preparing",
                        max_length=20,
                    ),
                ),
                ("tracking_number", models.CharField(blank=True, max_length=255)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "curation_type",
                    models.CharField(
                        choices=[
                            ("auto", "Auto-curated"),
                            ("manual", "Manual override"),
                        ],
                        default="auto",
                        help_text="Whether this shipment was auto-curated or manually selected",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="shipments", to="commerce.product"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="commerce.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_shipments",
                "ordering": ["-created_at"],
            },
        ),
    ]
