# Generated by Django 6.0.4 on 2026-04-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="next_curation_override",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Manual product selection for next shipment. Format: {'product_ids': [1, 2, 3]}",
                null=True,
            ),
        ),
    ]
